### ISSUE TITLE
Clarify the origin in matrix in `get_incidents_in_route_sjoin`

### ISSUE THREAD

**Issue by edarin** [GISRedeDev/PyNetworkFriction#25]
The function `get_incidents_in_route_sjoin` ([here](https://github.com/GISRedeDev/PyNetworkFriction/blob/16ecf5695bc47272a30ab2124ca8e7fa16cc658a/net_friction/calculations.py#L153)) requires `matrix` that seems to be the output of `get_route_geoms_ids` ([here](https://github.com/GISRedeDev/PyNetworkFriction/blob/16ecf5695bc47272a30ab2124ca8e7fa16cc658a/net_friction/calculations.py#L133)).

Therefore: 
1. it will be good to save this object (typically in the function [`data_processing`](https://github.com/GISRedeDev/PyNetworkFriction/blob/16ecf5695bc47272a30ab2124ca8e7fa16cc658a/net_friction/data_preparation.py#L317C5-L317C24))
2. if it is save and then read as a csv, the column `edge_geometries_ids` is read as a string and not a list which fails the .explode method. Therefore this line would need to be added `matrix['edge_geometries_ids'] = matrix['edge_geometries_ids'].apply(ast.literal_eval)
` in `get_incidents_in_route_sjoin`, I think.

**Comment by GISRedeDev** [comment]
I understand what you mean and I appreciate it's frustrating when the wrong data types are read into dataframes, but I would like to keep the functions as low-level as possible and leave it to the user to decide where and when to save outputs. This function (`data_pre_processing`) is just to help users access the network they need quickly in future iterations. The functionality is there for users to create the matrix when they need it, and it doesn't have to much overhead relative to the other pre-processing. 

If you are saving this intermediate table in your workflow, then I can only suggest that you apply that fix before passing your table to `get_incidents_in_route_sjoin`. I try not to use `ast.literal_eval` unsupervised as I've had unintended consequences when dask.dataframes are involved.
